spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  sql:
    init:
      data-locations: classpath*:db/h2/schema.sql
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

mail:
  address:
    admin: ${ADMIN_MAIL} # 관리자 이메일
